#!/usr/bin/env python3
"""Build a program that references every function the target headers declare.

A header that declares a name the library does not define is a program that
compiles and then fails at link, which is the worst place to find out: the
diagnostic names a symbol rather than the header that promised it. The target
headers exist so that a program written for a hosted system runs here unchanged,
and that promise is only true if every name in them is answerable.

The program is generated from the headers themselves rather than written out, so
a declaration added without a definition fails this check without anything
having to remember to extend a list.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGET_HEADERS = ROOT / "include" / "target"

# A declaration at the start of a line, ending in a semicolon, whose declarator
# names a function: an opening parenthesis before the name and a closing one
# before the semicolon. A macro is excluded because its body has no semicolon
# at the end of a declaration, and a typedef is excluded because a
# function-pointer typedef spells a type name where a function declaration
# would spell the function.
DECLARATION = re.compile(
    r"^(?!typedef\b)[A-Za-z_][^;{}#]*?\b([a-z_][a-z_0-9]*)\s*\([^;{}]*\)\s*;",
    re.MULTILINE)
# A name the header spells but that is not a function of the library: the
# compiler's own interface, whose definitions live in the compiler.
NOT_A_LIBRARY_FUNCTION = {
    "__cc64_va_start",
    "cc64_va_end",
    "cc64_va_copy",
    "cc64_va_arg",
}


def declarations() -> list[tuple[str, str]]:
    """Every declared function, with the header that declares it."""
    found: dict[str, str] = {}
    for path in sorted(TARGET_HEADERS.rglob("*.h")):
        relative = path.relative_to(TARGET_HEADERS).as_posix()
        for match in DECLARATION.finditer(path.read_text(encoding="utf-8")):
            name = match.group(1)
            if name in NOT_A_LIBRARY_FUNCTION or name in found:
                continue
            found[name] = relative
    return sorted(found.items())


def program() -> str:
    entries = declarations()
    includes = "\n".join(
        f'#include <{path.relative_to(TARGET_HEADERS).as_posix()}>'
        for path in sorted(TARGET_HEADERS.rglob("*.h")))
    lines = [
        "/* Generated by tests/declared_symbols.py from the target headers.",
        "   Every name below is a promise one of those headers makes to a",
        "   program, so every one of them has to answer at link time. */",
        includes,
        "",
        "int main(void) {",
    ]
    for name, header in entries:
        lines.append(f"    if (&{name} == 0) return 1;  /* {header} */")
    lines += [
        "    return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", default=None,
                        help="write the program here instead of to stdout")
    arguments = parser.parse_args()
    text = program()
    if arguments.output is None:
        sys.stdout.write(text)
    else:
        pathlib.Path(arguments.output).write_text(text, encoding="utf-8")
    print(f"declared-symbols: {len(declarations())} declared functions",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
